### ISSUE TITLE
Ciągłe ładowanie

### ISSUE THREAD

**Issue by beredentod** [mypolitics/mypolitics#15]
Po próbie włączenia quizu, już na pierwszym pytaniu, pojawia się animacja ładownia, która się nie wyłącza. Problem pojawia się zarówno na telefonie, jak i na komputerze.

**Comment by AdrianOrlow** [comment]
Problem związany z ograniczeniami CORS, wynikał z pozostawienia starej domeny w url'u API. Naprawiony w 6df04a8b9117b99bf1970ae1499cea254dcc1153
