### ISSUE TITLE
Złe efekty przy pytaniu

### ISSUE THREAD

**Issue by werixx** [mypolitics/mypolitics#24]
Pytanie 39
Prawo do aborcji nie powinno być regulowane:
zgoda powinna być tradycjonalizm i anarchizm
niezgoda powinna być autorytaryzm i progresywizm
Regulowanie aborcji jest progresywne a nie tradycjonalne

**Comment by Flavros** [comment]
Regulowanie aborcji jest tradycjonalne (teraz jest np. ograniczona do 3 przypadków). Jeszcze większym "tradycjonalizmem" byłoby całkowite jej zakazanie.
Nieregulowanie jej natomiast oznaczałoby mniej więcej całkowitą zgodę na aborcję, co (przynajmniej do określonego momentu rozwoju płodu) jest progresywne.
